<?php

/**
 * Local Home Index Hotkey Report Download
 *
 * Localhost-only endpoint that serves a verification CSV generated by
 * api/local-index-start.php. It accepts only a server-generated run ID and
 * never accepts a filesystem path from the request.
 *
 * GET /api/local-index-report.php?run=YYYYMMDD_HHMMSS_xxxxxxxx
 */

require_once __DIR__ . '/../includes/auth.php';

function localIndexReportRespond(int $statusCode, string $message): void
{
    http_response_code($statusCode);
    header('Content-Type: text/plain; charset=utf-8');
    header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
    header('Pragma: no-cache');
    echo $message;
    exit;
}

function localIndexReportIsLocalRequest(): bool
{
    $remoteAddress = $_SERVER['REMOTE_ADDR'] ?? '';

    return in_array($remoteAddress, [
        '127.0.0.1',
        '::1',
        '::ffff:127.0.0.1',
        '172.19.0.1',
        '::ffff:172.19.0.1',
    ], true);
}

function localIndexReportStatusDirectory(): string
{
    return rtrim(getenv('INDEX_STATUS_DIR') ?: '/system/index-status', '/');
}

if ($_SERVER['REQUEST_METHOD'] !== 'GET') {
    localIndexReportRespond(405, 'Method not allowed.');
}

if (!localIndexReportIsLocalRequest()) {
    localIndexReportRespond(403, 'This report is available only from localhost.');
}

$runId = isset($_GET['run']) && is_string($_GET['run'])
    ? $_GET['run']
    : '';

if (!preg_match('/^\d{8}_\d{6}_[a-f0-9]{8}$/', $runId)) {
    localIndexReportRespond(400, 'Invalid report identifier.');
}

$statusDirectory = localIndexReportStatusDirectory();
$baseDirectory = realpath($statusDirectory);

if ($baseDirectory === false || !is_dir($baseDirectory)) {
    localIndexReportRespond(500, 'The report directory is unavailable.');
}

$reportName = 'local-index-verification-' . $runId . '.csv';
$reportPath = realpath($baseDirectory . DIRECTORY_SEPARATOR . $reportName);

if ($reportPath === false || !is_file($reportPath)) {
    localIndexReportRespond(404, 'The verification report was not found.');
}

$requiredPrefix = rtrim($baseDirectory, DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR;

if (strpos($reportPath, $requiredPrefix) !== 0) {
    localIndexReportRespond(403, 'Invalid report location.');
}

if (!is_readable($reportPath)) {
    localIndexReportRespond(500, 'The verification report is not readable.');
}

$downloadName = 'edutek-index-verification-' . $runId . '.csv';

header('Content-Type: text/csv; charset=utf-8');
header('Content-Disposition: attachment; filename="' . $downloadName . '"');
header('Content-Length: ' . (string) filesize($reportPath));
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
header('Pragma: no-cache');

readfile($reportPath);
exit;