<?php

/**
 * Local Catalog Cleanup Report Download
 *
 * Localhost-only endpoint that serves a cleanup CSV generated by
 * api/local-catalog-cleanup-start.php.
 *
 * GET /api/local-catalog-cleanup-report.php?run=YYYYMMDD_HHMMSS_xxxxxxxx
 */

require_once __DIR__ . '/../includes/auth.php';

function cleanupReportRespond(int $statusCode, string $message): void
{
    http_response_code($statusCode);
    header('Content-Type: text/plain; charset=utf-8');
    header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
    header('Pragma: no-cache');
    echo $message;
    exit;
}

function cleanupReportIsLocalRequest(): bool
{
    $remoteAddress = $_SERVER['REMOTE_ADDR'] ?? '';

    return in_array($remoteAddress, [
        '127.0.0.1',
        '::1',
        '::ffff:127.0.0.1',
        '172.19.0.1',
        '::ffff:172.19.0.1',
    ], true);
}

function cleanupReportStatusDirectory(): string
{
    return rtrim(getenv('INDEX_STATUS_DIR') ?: '/system/index-status', '/');
}

if ($_SERVER['REQUEST_METHOD'] !== 'GET') {
    cleanupReportRespond(405, 'Method not allowed.');
}

if (!cleanupReportIsLocalRequest()) {
    cleanupReportRespond(403, 'This report is available only from localhost.');
}

$runId = isset($_GET['run']) && is_string($_GET['run'])
    ? $_GET['run']
    : '';

if (!preg_match('/^\d{8}_\d{6}_[a-f0-9]{8}$/', $runId)) {
    cleanupReportRespond(400, 'Invalid report identifier.');
}

$statusDirectory = cleanupReportStatusDirectory();
$baseDirectory = realpath($statusDirectory);

if ($baseDirectory === false || !is_dir($baseDirectory)) {
    cleanupReportRespond(500, 'The report directory is unavailable.');
}

$reportName = 'local-catalog-cleanup-' . $runId . '.csv';
$reportPath = realpath($baseDirectory . DIRECTORY_SEPARATOR . $reportName);

if ($reportPath === false || !is_file($reportPath)) {
    cleanupReportRespond(404, 'The cleanup report was not found.');
}

$requiredPrefix = rtrim($baseDirectory, DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR;

if (strpos($reportPath, $requiredPrefix) !== 0) {
    cleanupReportRespond(403, 'Invalid report location.');
}

if (!is_readable($reportPath)) {
    cleanupReportRespond(500, 'The cleanup report is not readable.');
}

$downloadName = 'edutek-catalog-cleanup-' . $runId . '.csv';

header('Content-Type: text/csv; charset=utf-8');
header('Content-Disposition: attachment; filename="' . $downloadName . '"');
header('Content-Length: ' . (string) filesize($reportPath));
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
header('Pragma: no-cache');

readfile($reportPath);
exit;
